// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_cPloez7DNMcutFvhvglaIHHjOFLyWCE',
    appId: '1:998073285058:web:856c74511357abffbb7e5b',
    messagingSenderId: '998073285058',
    projectId: 'lab07-5a1f2',
    authDomain: 'lab07-5a1f2.firebaseapp.com',
    storageBucket: 'lab07-5a1f2.appspot.com',
    measurementId: 'G-KDJ8B97W07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8qlX1ehX0LpHphuL8tq1oN_KFc2msn8',
    appId: '1:998073285058:android:755522c87805c1f9bb7e5b',
    messagingSenderId: '998073285058',
    projectId: 'lab07-5a1f2',
    storageBucket: 'lab07-5a1f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1Uc0RLbepCsssx-n_HQ8H2SIsbZA6Vw',
    appId: '1:998073285058:ios:09c076803d490ce9bb7e5b',
    messagingSenderId: '998073285058',
    projectId: 'lab07-5a1f2',
    storageBucket: 'lab07-5a1f2.appspot.com',
    iosClientId: '998073285058-s7l95e2r7n4bpugc85pnuldin2pnmfcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab07google',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa1Uc0RLbepCsssx-n_HQ8H2SIsbZA6Vw',
    appId: '1:998073285058:ios:09c076803d490ce9bb7e5b',
    messagingSenderId: '998073285058',
    projectId: 'lab07-5a1f2',
    storageBucket: 'lab07-5a1f2.appspot.com',
    iosClientId: '998073285058-s7l95e2r7n4bpugc85pnuldin2pnmfcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab07google',
  );
}
